# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/RSNA-_Breast_Cancer_Detection',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/RSNA-_Breast_Cancer_Detection',
                'lib_path': 'RSNA__Breast_Cancer_Detection'},
  'syms': { 'RSNA__Breast_Cancer_Detection.core': { 'RSNA__Breast_Cancer_Detection.core.foo': ( 'core.html#foo',
                                                                                                'RSNA__Breast_Cancer_Detection/core.py')}}}